accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from accounts.views import register_new_user

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", register_new_user, name="signup"),
]

projects/urls.py
from django.urls import path

from projects.views import (
    ProjectCreateView,
    ProjectDetailView,
    ProjectListView,
)

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
    path("create/", ProjectCreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path

from tasks.views import TaskCreateView, TaskListView, TaskUpdateView

urlpatterns = [
    path("create/", TaskCreateView.as_view(), name="create_task"),
    path("mine/", TaskListView.as_view(), name="show_my_tasks"),
    path(
        "<int:pk>/complete/",
        TaskUpdateView.as_view(),
        name="complete_task",
    ),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("", RedirectView.as_view(url="/projects/"), name="home"),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        "projects.Project", related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, related_name="tasks", on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


def register_new_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()

    context = {"form": form}
    return render(request, "registration/signup.html", context)

projects/views.py
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from projects.models import Project


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"
    context_object_name = "project"


class ProjectCreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "projects/create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", kwargs={"pk": self.object.pk})

tasks/views.py
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from tasks.models import Task


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "tasks/create.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy(
            "show_project", kwargs={"pk": self.object.project.pk}
        )


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "tasks/list.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ["is_completed"]

    def get_success_url(self):
        return reverse_lazy("show_my_tasks")

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %}Matt's Project Alpha {% endblock title %}
        </title>
    </head>
    <body>
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'show_my_tasks' %}">My Tasks</a></li>
                        <li><a href="{% url 'list_projects' %}">My Projects</a></li>
                        {% comment %} Added username to logout link for better
                    clarity. {% endcomment %}
                        <li>
                            <!-- prettier-ignore -->
                            <a href="{% url 'logout' %}" >Logout ({{ user.username }})</a >
                        </li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        {% block content %} {% endblock content %}
    </body>
</html>

projects/templates/projects/create.html
<!-- prettier-ignore -->
{% extends 'base.html' %} {% block title %}Create New Project{% endblock title %}

<!-- prettier-ignore -->
{% block content %}
    <main>
        <div>
            <h1>Create a new project</h1>
            <form method="post">
                {% csrf_token %} {{ form.as_p }}
                <button>Create</button>
            </form>
        </div>
    </main>
{% endblock content %}

projects/templates/projects/detail.html
<!-- prettier-ignore -->
{% extends 'base.html' %} {% block title %}{{ project.name }}{% endblock title %} {% load markdownify %}

<!-- prettier-ignore -->
{% block content %}
    <main>
        <div>
            <h1>{{ project.name }}</h1>
            <p>{{ project.description|markdownify }}</p>
            <h2>Tasks</h2>
            <p><a href="{% url 'create_task' %}">Create a new task</a></p>
            {% if project.tasks.all|length > 0 %}
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Assignee</th>
                        <th>Start date</th>
                        <th>Due date</th>
                        <th>Is completed</th>
                    </thead>
                    <tbody>
                        {% for task in project.tasks.all %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.assignee }}</td>
                                <td>{{ task.start_date|date:"m/d/Y" }}</td>
                                <td>{{ task.due_date|date:"m/d/Y" }}</td>
                                <td>{{ task.is_completed }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>This project has no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

projects/templates/projects/list.html
{% extends 'base.html' %} {% block title %}My Projects{% endblock title %}

<!-- prettier-ignore -->
{% block content %}
    <main>
        <div>
            <h1>My Projects</h1>
            <p><a href="{% url 'create_project' %}">Create a new project</a></p>
            {% if project_list.all|length > 0 %}
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Number of tasks</th>
                    </thead>
                    <tbody>
                        {% for project in project_list %}
                            <tr>
                                <td>
                                    <!-- prettier-ignore -->
                                    <a href="{% url 'show_project' project.pk %}">{{ project.name }}</a>
                                </td>
                                <td>{{ project.members.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You are not assigned to any projects</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/create.html
<!-- prettier-ignore -->
{% extends 'base.html' %} {% block title %}Create New Task{% endblock title %}

<!-- prettier-ignore -->
{% block content %}
    <main>
        <div>
            <h1>Create a new task</h1>
            <form method="post">
                {% csrf_token %} {{ form.as_p }}
                <button>Create a new task</button>
            </form>
        </div>
    </main>
{% endblock content %}

tasks/templates/tasks/list.html
{% extends 'base.html' %} {% block title %}My Tasks{% endblock title %}

<!-- prettier-ignore -->
{% block content %}
    <main>
        <div>
            <h1>My Tasks</h1>
            {% if task_list.all|length > 0 %}
                <table>
                    <thead>
                        <th>Name</th>
                        <th>Start date</th>
                        <th>End date</th>
                        <th>Is completed</th>
                    </thead>
                    <tbody>
                        {% for task in task_list %}
                            <tr>
                                <td>{{ task.name }}</td>
                                <td>{{ task.start_date|date:"m/d/Y" }}</td>
                                <td>{{ task.due_date|date:"m/d/Y" }}</td>
                                <td>
                                    {% if task.is_completed %} Done {% else %}
                                        <form
                                            action="{% url 'complete_task' task.id %}"
                                            method="post"
                                        >
                                            {% csrf_token %}
                                            <input
                                                type="hidden"
                                                name="is_completed"
                                                value="True"
                                            />
                                            <button>Complete</button>
                                        </form>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>You have no tasks</p>
            {% endif %}
        </div>
    </main>
{% endblock content %}